name: Update Stock Website

on:
  schedule:
    - cron: '45 15 * * 1-5'
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Required to allow the bot to push back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Data Script
        run: python update_website.py

      - name: Force Commit and Push JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m "Automated update of data.json" || true
          git push